-- Ceche Comparisons Seed Data

-- GoDaddy
INSERT INTO comparisons (competitor, slug, rows_data, meta_title, meta_description) VALUES
('GoDaddy', 'godaddy',
 '[{"feature":"Valuation Modules","ceche":"16","competitor":"5-7"},
   {"feature":"AI-Powered","ceche":"Yes — segmentation, CPC, trademark","competitor":"Limited"},
   {"feature":"Bulk Appraisal","ceche":"Unlimited via CLI","competitor":"Limited, paid"},
   {"feature":"API Access","ceche":"REST API built-in","competitor":"Separate paid API"},
   {"feature":"Open Source","ceche":"Yes — MIT license","competitor":"No"},
   {"feature":"Price","ceche":"Free CLI, $49 per month API","competitor":"$5 to $50 per appraisal"},
   {"feature":"Transparency","ceche":"Full module breakdown","competitor":"Black box estimate"},
   {"feature":"Terminal UI","ceche":"Yes — Textual-based","competitor":"No"},
   {"feature":"Offline Mode","ceche":"Yes — runs fully offline","competitor":"No"},
   {"feature":"Self-Hostable","ceche":"Yes — Docker deploy","competitor":"No"},
   {"feature":"Data Sources","ceche":"RDAP, Ahrefs, OPR, Google, Wayback, USPTO","competitor":"Proprietary"},
   {"feature":"Trademark Detection","ceche":"USPTO database plus AI","competitor":"No"},
   {"feature":"Authority Signals","ceche":"Ahrefs DR, OPR score, Wayback snapshots","competitor":"Proprietary"},
   {"feature":"Cache System","ceche":"Configurable TTL per adapter","competitor":"Unknown"},
   {"feature":"Custom Modules","ceche":"Yes — extensible architecture","competitor":"No"},
   {"feature":"Community Support","ceche":"GitHub discussions, open contributions","competitor":"Paid support only"}]',
 'Ceche vs GoDaddy Domain Appraisal Comparison',
 'Compare Ceche domain appraisal with GoDaddy Appraisal. Ceche offers 16 modules, open source code, bulk appraisal, and full transparency at no cost.'),

-- Dynadot
('Dynadot', 'dynadot',
 '[{"feature":"Valuation Modules","ceche":"16","competitor":"6"},
   {"feature":"AI-Powered Segmentation","ceche":"Yes — optional AI enhancement","competitor":"Limited"},
   {"feature":"Bulk Appraisal","ceche":"Unlimited via CLI","competitor":"Not available"},
   {"feature":"REST API","ceche":"Yes — full CRUD endpoints","competitor":"No"},
   {"feature":"Open Source","ceche":"Yes — MIT license","competitor":"No"},
   {"feature":"Price","ceche":"Free CLI, $49 per month API","competitor":"Free basic"},
   {"feature":"Module Transparency","ceche":"Full breakdown per module","competitor":"Opaque"},
   {"feature":"CLI Tool","ceche":"Yes — 49 commands","competitor":"No"},
   {"feature":"Terminal UI","ceche":"Yes — Textual-based TUI","competitor":"No"},
   {"feature":"Self-Hosted Option","ceche":"Yes — Docker Compose","competitor":"No"},
   {"feature":"Trademark Detection","ceche":"USPTO plus AI enhancement","competitor":"No"},
   {"feature":"Authority Signals","ceche":"Ahrefs, OPR, Wayback Machine","competitor":"No"},
   {"feature":"Customizable Weights","ceche":"Yes — per weight profile","competitor":"No"},
   {"feature":"Portfolio Management","ceche":"Yes — built-in portfolio system","competitor":"No"}]',
 'Ceche vs Dynadot Domain Appraisal Comparison',
 'Compare Ceche domain valuation with Dynadot. Ceche provides 16 modules, CLI and TUI interfaces, open source code, and transparent module breakdown.'),

-- Estibot
('Estibot', 'estibot',
 '[{"feature":"Valuation Modules","ceche":"16","competitor":"5"},
   {"feature":"AI Enhancement","ceche":"Optional AI for all modules","competitor":"Limited scope"},
   {"feature":"Bulk Appraisal","ceche":"Unlimited concurrent","competitor":"Paid only"},
   {"feature":"API Access","ceche":"REST API included","competitor":"Paid API tier"},
   {"feature":"Open Source","ceche":"Yes — MIT license","competitor":"No"},
   {"feature":"Price","ceche":"Free CLI, $49 per month API","competitor":"$5 to $50 per report"},
   {"feature":"Module Breakdown","ceche":"Full per-module transparency","competitor":"Limited detail"},
   {"feature":"CLI Tool","ceche":"Yes — 49 commands","competitor":"No"},
   {"feature":"Terminal UI","ceche":"Yes — Textual","competitor":"No"},
   {"feature":"Offline Appraisal","ceche":"Yes — no internet required","competitor":"No"},
   {"feature":"Self-Hosted","ceche":"Yes — Docker deployment","competitor":"No"},
   {"feature":"Trademark Checking","ceche":"USPTO database plus AI","competitor":"No"},
   {"feature":"Authority Data","ceche":"Ahrefs, OPR, Wayback Machine","competitor":"Proprietary"},
   {"feature":"Cache System","ceche":"Configurable TTL","competitor":"Unknown"}]',
 'Ceche vs Estibot Domain Appraisal Comparison',
 'Compare Ceche domain valuation with Estibot. Ceche offers more modules, full transparency, AI enhancement, open source code, and lower pricing.');
