FROM node:20-slim AS builder

WORKDIR /app
COPY web/package.json web/package-lock.json ./
RUN npm ci --legacy-peer-deps
COPY web/ .
RUN npm run build

FROM node:20-slim

RUN adduser --disabled-password --gecos '' ceche

COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json

USER ceche
EXPOSE 4321
WORKDIR /app
CMD ["node", "dist/server/entry.mjs"]
